src/Entity/Artwork.php
<?php

namespace App\Entity;

use App\Repository\ArtworkRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ArtworkRepository::class)]
class Artwork
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $title;

    #[ORM\Column(type: 'text')]
    private $picture;

    #[ORM\Column(type: 'integer')]
    private $format1;

    #[ORM\Column(type: 'integer')]
    private $format2;

    #[ORM\Column(type: 'string', length: 255)]
    private $categorie;

    #[ORM\Column(type: 'date')]
    private $creationDate;

    #[ORM\ManyToOne(targetEntity: Administrator::class)]
    #[ORM\JoinColumn(nullable: false)]
    private $admin;

    #[ORM\Column(type: 'boolean')]
    private $type;



    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(string $picture): self
    {
        $this->picture = $picture;

        return $this;
    }

    public function getFormat(): ?int
    {
        return $this->format1;
    }

    public function setFormat(int $format1): self
    {
        $this->format1 = $format1;

        return $this;
    }
    public function getFormat2(): ?int
    {
        return $this->format2;
    }

    public function setFormat2(int $format2): self
    {
        $this->format2 = $format2;

        return $this;
    }
    public function getCategorie(): ?string
    {
        return $this->categorie;
    }

    public function setCategorie(string $categorie): self
    {
        $this->categorie = $categorie;

        return $this;
    }

    public function getCreationDate(): ?\DateTimeInterface
    {
        return $this->creationDate;
    }

    public function setCreationDate(\DateTimeInterface $creationDate): self
    {
        $this->creationDate = $creationDate;

        return $this;
    }

    public function getAdmin(): ?Administrator
    {
        return $this->admin;
    }

    public function setAdmin(?Administrator $admin): self
    {
        $this->admin = $admin;

        return $this;
    }

    public function getType(): ?bool
    {
        return $this->type;
    }

    public function setType(bool $type): self
    {
        $this->type = $type;

        return $this;
    }

    
}

src/Controller/VitrineWebsiteController.php
<?php

namespace App\Controller;

use App\Entity\Contact;
use App\Repository\ArtworkRepository;
use App\Repository\ExpositionRepository;
use App\Repository\WebsiteSaveRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormFactoryInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class VitrineWebsiteController extends AbstractController
{
    /** 
      * @Route("/", name="about" )
    */
    public function index(FormFactoryInterface $factory, Request $request, WebsiteSaveRepository $websiteSaveRepository, EntityManagerInterface $em): Response
    {
        $builder = $factory->createBuilder();
        $error = '';
        $builder->add('name', TextType::class, [
                'label' => false,
                'required' => true,  
        ])
        ->add('firstname', TextType::class, [
          'label' => false,
          'required' => true,       
        ])
        ->add('mail', EmailType::class, [
          'label' => false,
          'required' => true,       
        ])
        ->add('phone', NumberType::class, [
          'label' => false,
          'required' => true,  
        ])
        ->add('capcha', NumberType::class, [
          'label' => false,
          'required' => true,  
        ])
        ->add('message', TextareaType::class, [
            'label' => false,
            'required' => true,
        ])
      ;

        $form = $builder->getForm();
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {


          $data = $form->getData();
          $contact = new Contact;
        
          if($data['capcha'] == 10){
            $contact->setName($data['name'])
            ->setFirstname($data['firstname'])
            ->setMail($data['mail'])
            ->setPhone($data['phone'])
            ->setMessage($data['message'])
            ->setDate(new \DateTime());
        
            $em->persist($contact);
            $em->flush();
            
            $form = $builder->getForm();
            return $this->redirect("/#contact");
          }else{
            $error = 'Le chiffre clé est 10 !';
          }

         

        }
        $formView = $form->createView();

        return $this->render('vitrine_website/index.html.twig', [
            'galeryMenu' => '',
            'aboutMenu' => 'active',
            'expositionMenu' => '',

            'formView' => $formView,
            'error' => $error,
            'titleSave' => $websiteSaveRepository->find(1)->getContent(),
            'textFirstSave' => $websiteSaveRepository->find(2)->getContent(),
            'imageFirstSave' => $websiteSaveRepository->find(3)->getContent(),
            'textBiographie' => $websiteSaveRepository->find(5)->getContent(),
            'imageBiographie' => $websiteSaveRepository->find(4)->getContent(),
            'mailSave' => $websiteSaveRepository->find(6)->getContent(),
        ]);
    }

    /** 
      * @Route("/galerie", name="galerie" )
    */
    public function galerie(ArtworkRepository $artworkRepository): Response
    {
        $artworks = $artworkRepository->findAll();

        return $this->render('vitrine_website/galerie.html.twig', [
            'galeryMenu' => 'active',
            'aboutMenu' => '',
            'expositionMenu' => '',
            'artworks'=>$artworks
        ]);
    }

    /** 
      * @Route("/expositions", name="expositions" )
    */
    public function expositions(ExpositionRepository $expositionRepository): Response
    {
        $expositions = $expositionRepository->findAll();

        return $this->render('vitrine_website/expositions.html.twig', [
            'galeryMenu' => '',
            'aboutMenu' => '',
            'expositionMenu' => 'active',
            'expositions'=> $expositions
        ]);
    }

    /** 
      * @Route("/galerie-oeuvre/{id}", name="galerie_oeuvre" )
    */
    public function galerie_oeuvre($id, ArtworkRepository $artworkRepository): Response
    {
        $artworks = $artworkRepository->findAll();

        return $this->render('vitrine_website/galerie_oeuvre.html.twig', [
            'artworks'=>$artworks,
            'idArt' => $id
            
        ]);
    }

    /** 
      * @Route("/mentions-legales", name="mentions_legales" )
    */
    public function mention(): Response
    {
       

        return $this->render('vitrine_website/mention.html.twig', [
          'galeryMenu' => '',
          'aboutMenu' => '',
          'expositionMenu' => '',
            
        ]);
    }

     /** 
      * @Route("/politiques-confidentialites", name="politiques_confidentialites" )
    */
    public function politique(): Response
    {
       

        return $this->render('vitrine_website/politique.html.twig', [
          'galeryMenu' => '',
          'aboutMenu' => '',
          'expositionMenu' => '',
            
        ]);
    }
    
    /** 
      * @Route("/perdu-sur-mon-site", name="page_404" )
    */
    public function lost_page(WebsiteSaveRepository $websiteSaveRepository): Response
    {
        

        return $this->render('vitrine_website/index.html.twig', [
            'galeryMenu' => '',
            'aboutMenu' => '',
            'expositionMenu' => '',


            'titleSave' => $websiteSaveRepository->find(1)->getContent(),
            'textFirstSave' => $websiteSaveRepository->find(2)->getContent(),
            'imageFirstSave' => $websiteSaveRepository->find(3)->getContent(),
            'textBiographie' => $websiteSaveRepository->find(5)->getContent(),
            'imageBiographie' => $websiteSaveRepository->find(4)->getContent(),
            'mailSave' => $websiteSaveRepository->find(6)->getContent(),
        ]);
    }
}

templates/vitrine_website/expositions.html.twig
{% extends 'base.html.twig' %}

{% block title %}Benoit Fabioux - Expositions{% endblock %}

{% block body %}
    <section id="exposition-section">
       <div class="container-exposition">
            <h1>Expositions</h1>
            {% for exposition in expositions %}
                <div class="contenu-exposition">
                    <div class="image-container">
                        <img src='{{ exposition.picture }}'/>
                    </div>
                    <div class='text-container'>
                        <h2>{{ exposition.title|upper }}</h2>
                        <p>{{ exposition.text }}</p>
                    </div>
                </div>
            {% endfor %}    
       </div>
   
        <div class='mentions-legales'>
            <p id="right-paragraph">©2022 Tous droits réservés Benoit Fabioux</p>
            <div>
                <a href="{{ path ('mentions_legales') }}">
                    <p>Mentions légales</p>
                </a>
                <a href="{{ path ('politiques_confidentialites') }}">
                    <p>Politique de confidentialités</p>
                </a>
            </div>
        </div>
    </section>

    <script> 
        let date = new Date();
        document.getElementById('right-paragraph').innerHTML = "©"+date.getFullYear()+" Tous droits réservés Benoit Fabioux";
    </script>
{% endblock %}

templates/vitrine_website/galerie.html.twig
{% extends 'base.html.twig' %}

{% block title %}Benoit Fabioux - Galerie{% endblock %}

{% block javascripts %}
<script>
    window.onscroll = function(ev) {
        if ((window.innerHeight + window.scrollY) >= document.body.offsetHeight) {
            document.getElementById('mouse-scroll').classList.add('un-active');
            document.getElementById('roll-up-button').classList.remove('un-active');
        }else{
            document.getElementById('mouse-scroll').classList.remove('un-active');
            document.getElementById('roll-up-button').classList.add('un-active');
        }
    };

    function categoryChange(category){
        if(category === 'huile'){   
            document.body.classList.remove('dark-theme');

            document.getElementById('huile-category').classList.add('active');
            document.getElementById('acrylique-category').classList.remove('active');

        }else if(category === 'acrylique'){
           
            document.body.classList.add('dark-theme');

            document.getElementById('huile-category').classList.remove('active');
            document.getElementById('acrylique-category').classList.add('active');

        }
    }

</script>
           
{% endblock %}

{% block body %}
    <div id="action-right-bottom">
        <div id="mouse-scroll" class="mouse_btn">
            <a class="smooth" href="#qui_est_il">
                <span class="mouse">
                    <span>
                    </span>
                </span>
            </a>
            <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
        </div>
        <div id="roll-up-button" class="roll-up-button-g un-active" onclick="window.scrollTo({top: 0, behavior: 'smooth'});">
            <div></div>
        </div>
    </div>

    <section id="button-category-section">
        <div id="button-category-container" class="button-category-container">
            <div id="huile-category" onclick="categoryChange('huile')" class="active"><p>Huile</p></div>
            <div id="acrylique-category" onclick="categoryChange('acrylique')"><p>Acrylique</p></div>
        </div>
    </section>

    <section id="galery-section">
        <div class="galery-container">

            
                <div class=" container huile-section">
                    {% for artwork in artworks %}
                        
                        {% if artwork.categorie == 'Huile' %}
                            <div  class="galery-contenu">
                                    {% if artwork.type == true %}
                                    <div style="width:75%">

                                        <div class="image-contenu" >
                                            <a href='{{ path ('galerie_oeuvre', {'id': artwork.id}) }}'>
                                                <img src="{{ artwork.picture }}"/>
                                            </a>    
                                        </div> 
                                    {% else %}
                                     <div style="width:100%">

                                        <div class="image-contenu" >
                                            <a href='{{ path ('galerie_oeuvre', {'id': artwork.id}) }}'>
                                                <img src="{{ artwork.picture }}"/>
                                            </a>                                         
                                        </div> 
                                    {% endif %}  
                                    
                                <h1>{{ artwork.title|upper }}</h1>
                                <p><span>{{ artwork.categorie|capitalize }} |</span> {{ artwork.format }} x {{ artwork.format2 }}</p>
                            </div>
                            </div>
                        {% endif %}  
                    {% endfor %}  
                </div>
                <div class="container acrylyque-section">
                    {% for artwork in artworks %}
                        
                        {% if artwork.categorie == 'Acrylique' %}
                            <div  class="galery-contenu">
                                     {% if artwork.type == true %}
                                    <div style="width:75%">

                                        <div class="image-contenu" >
                                            <a href='{{ path ('galerie_oeuvre', {'id': artwork.id}) }}'>
                                                <img src="{{ artwork.picture }}"/>
                                            </a>    
                                        </div> 
                                    {% else %}
                                     <div style="width:100%">

                                        <div class="image-contenu" >
                                            <a href='{{ path ('galerie_oeuvre', {'id': artwork.id}) }}'>
                                                <img src="{{ artwork.picture }}"/>
                                            </a>                                         
                                        </div> 
                                    {% endif %}  
                                    
                                <h1>{{ artwork.title|upper }}</h1>
                                <p><span>{{ artwork.categorie|capitalize }} |</span> {{ artwork.format }} x {{ artwork.format2 }}</p>
                            </div>
                            </div>
                        {% endif %}  
                    {% endfor %}  
                </div>
            
          

        </div>

        <div class='mentions-legales'>
            <p id="right-paragraph">©2022 Tous droits réservés Benoit Fabioux</p>

            <div>
                <a href="{{ path ('mentions_legales') }}">
                    <p>Mentions légales</p>
                </a>
                <a href="{{ path ('politiques_confidentialites') }}">
                    <p>Politique de confidentialités</p>
                </a>
            </div>
        </div>
    </section>

    <script> 
        let date = new Date();
        document.getElementById('right-paragraph').innerHTML = "©"+date.getFullYear()+" Tous droits réservés Benoit Fabioux";
    </script>

{% endblock %}

templates/vitrine_website/galerie_oeuvre.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>Benoit Fabioux - Galerie</title>
        <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text></svg>">
        {# Run `composer require symfony/webpack-encore-bundle` to start using Symfony UX #}
        <link rel="stylesheet" href="/css/style.css"/>
        {% block javascripts %}
            <script>
                var idTab = [] , tabLenght;
                var currentId = {{idArt}};


                function slideOn(side){
                    document.getElementById('arrow-left-nav-galerie').style.display = 'block';
                    document.getElementById('arrow-right-nav-galerie').style.display = 'block';
                    
                    if(side =='left'){
                        document.getElementById('arrow-right-nav-galerie').style.display = 'block';
                        document.getElementById('container-oeuvre-galerie-'+currentId).classList.remove('on-the-top');
                        document.getElementById('container-oeuvre-galerie-'+currentId).classList.add('on-the-right');
                        if(side == 'left'){
                                currentId--;                    
                        }else if(side == 'right'){
                                currentId++;
                            }

                        if(currentId <= idTab[0]){ 
                            document.getElementById('arrow-left-nav-galerie').style.display = 'none';
                        }
                        document.getElementById('container-oeuvre-galerie-'+currentId).classList.add('on-the-top');
                        document.getElementById('container-oeuvre-galerie-'+currentId).classList.remove('on-the-left');

                    }else if(side =='right'){
                        
                            document.getElementById('arrow-right-nav-galerie').style.display = 'block';
                            document.getElementById('container-oeuvre-galerie-'+currentId).classList.remove('on-the-top');
                            document.getElementById('container-oeuvre-galerie-'+currentId).classList.add('on-the-left');
                            if(side == 'left'){
                                currentId--;                    
                            }else if(side == 'right'){
                                currentId++;
                            }
                        if(currentId >= idTab[tabLenght-1]){
                            document.getElementById('arrow-right-nav-galerie').style.display = 'none';
                        }
                        document.getElementById('container-oeuvre-galerie-'+currentId).classList.add('on-the-top');
                        document.getElementById('container-oeuvre-galerie-'+currentId).classList.remove('on-the-right');

                    }
                    
                }
            </script>      
        {% endblock %}
    </head>
    <body>
        <a href='{{ path ('galerie') }}'><p id="return-galerie">Retourner à la galerie</p></a>
            
        <a onclick="slideOn('left')">
            <div id="arrow-left-nav-galerie" style='background-image:url("/image/icons/back.svg");' class="arrow-nav-galerie"></div>
        </a>
        <a onclick="slideOn('right')">
            <div id="arrow-right-nav-galerie" style='background-image:url("/image/icons/back.svg");' class="arrow-nav-galerie" ></div>
        </a>
            

        <section id="galerie-oeuvre-carroussel">
                

                 {% for artwork in artworks %}
                    <script>
                        tabLenght = idTab.push({{ artwork.id }});
              console.log(idTab)
                    </script>

                    <div id="container-oeuvre-galerie-{{ artwork.id }}" class="container-oeuvre-galerie">
                        <div class="contenu-oeuvre-galerie">
                            <img src="{{ artwork.picture }}"/>
                            <div>
                                <h2>{{ artwork.title|upper }}</h2>
                                <p>{{ artwork.categorie|capitalize }}</span> | {{ artwork.format }} x {{ artwork.format2 }}</p>
                            </div>
                        </div>
                    </div>
                {% endfor %}    
                

        </section>
    </body>
</html>

<script>
    function carousselSet( id ){

        idTab.forEach(otherId => {

            if(id > otherId){
                document.getElementById('container-oeuvre-galerie-'+otherId).classList.add('on-the-left');
            }else{
                document.getElementById('container-oeuvre-galerie-'+otherId).classList.add('on-the-right');
            }

        });
        document.getElementById('container-oeuvre-galerie-'+id).classList.remove('on-the-right');
        document.getElementById('container-oeuvre-galerie-'+id).classList.remove('on-the-left');
        document.getElementById('container-oeuvre-galerie-'+id).classList.add('on-the-top');
  
    }

    window.onload = carousselSet( '{{idArt}}' );
</script>      

templates/vitrine_website/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Benoit Fabioux - À propos{% endblock %}

{% block javascripts %}
    <script src="/js/wordCounter.js"></script>

    <script>
        function smoothScroll(target){
            document.getElementById('about-section-scroll').classList.remove('activeScroll');
            document.getElementById('biographie-section-scroll').classList.remove('activeScroll');
            document.getElementById('contact-section-scroll').classList.remove('activeScroll');

            document.getElementById(target+'-scroll').classList.add('activeScroll');

            document.getElementById(target).scrollIntoView({
                behavior: 'smooth'
            })
            history.pushState(null, null, hashval)
            e.preventDefault()
              
        }

        

        // Check si l'element passé en param est affiché sur l'écran
        function checkVisible(elm) {
            var rect = elm.getBoundingClientRect();
            var viewHeight = Math.max(document.documentElement.clientHeight, window.innerHeight);
            return !(rect.bottom < 0 || rect.top - viewHeight >= 0);
        }

        //Regarde si la div competence est affichée toutes les 250ms puis désactive l'interval
        setInterval(function() {
            if ( checkVisible(document.getElementById('about-section')))     {
            document.getElementById('about-section-scroll').classList.add('activeScroll');
            document.getElementById('biographie-section-scroll').classList.remove('activeScroll');
            document.getElementById('contact-section-scroll').classList.remove('activeScroll');
            
            }
        }, 50);

        setInterval(function() {
            if ( checkVisible(document.getElementById('biographie-section')))     {
            document.getElementById('about-section-scroll').classList.remove('activeScroll');
            document.getElementById('biographie-section-scroll').classList.add('activeScroll');
            document.getElementById('contact-section-scroll').classList.remove('activeScroll');
            
            }
        }, 50);

        setInterval(function() {
            if ( checkVisible(document.getElementById('contact-section'))){
            document.getElementById('about-section-scroll').classList.remove('activeScroll');
            document.getElementById('biographie-section-scroll').classList.remove('activeScroll');
            document.getElementById('contact-section-scroll').classList.add('activeScroll');
     
            }
        }, 50);
        
    </script>
{% endblock %}

{% block body %}

<div id="menu-scroll">
    <div></div>
    <a onclick="smoothScroll('about-section')"><p id='about-section-scroll' class="activeScroll">Accueil</p></a>
    <div></div>
    <a onclick="smoothScroll('biographie-section')"><p id='biographie-section-scroll'>Biographie</p></a>
    <div></div>
    <a onclick="smoothScroll('contact-section')"><p id='contact-section-scroll'>Contact</p></a>
    <div></div>
</div>

    <section id="about-section">
        <div class="about-container">
            <div class="about-container-section-left" >
                <img src="{{imageFirstSave}}" alt="Benoit Fabioux"/>
            </div>
            <div class="about-container-section-right">
                <h1>{{titleSave}}</h1>
                {% if textFirstSave != null %}
                <p>
                    <span>Breaking news :</span> {{textFirstSave}}
                </p>
                {% endif %}

            </div>
        </div>
    </section>
    <section id="biographie-section">
        <div class="biographie-container">
            <h1>Biographie</h1>
            <div class="row-biographie-container">
                <div>
                    <p id='text-biographie-1'></p>
                </div>
                <div class="middle-section">
                    <div class="img-middle-section" >
                        <img src="{{imageBiographie}}" alt="Benoit Fabioux"/>
                    </div>
                    <p id='text-biographie-2'>Le Lorem Ipsum est simplement du faux texte employé dans la composition et la mise en page avant impression. Le Lorem Ipsum est le faux texte standard de l’imprimerie depuis les années 1500, quand un imprimeur anonyme assembla ensemble des morceaux de texte pour réaliser un livre spécimen de polices de texte. Il n’a pas fait que survivre cinq</p>
                </div>
                <div>
                    <p id='text-biographie-3'>Le Lorem Ipsum est simplement du faux texte employé dans la composition et la mise en page avant impression. Le Lorem Ipsum est le faux texte standard de l’imprimerie depuis les années 1500, quand un imprimeur anonyme assembla ensemble des morceaux de texte pour réaliser un livre spécimen de polices de texte. Il n’a pas fait que survivre cinq siècles, mais s’est aussi adapté à la bureautique informatique, sans que son contenu n’en soit modifié. Il a été popularisé dans les années 1960 grâce à la vente de feuilles Letraset contenant des passages du Lorem Ipsum, et, plus récemment, par son inclusion dans des applications de mise en page de texte, comme Aldus PageMaker.</p>
                </div>
            </div>
        </div>
    </section>

    <section id="contact-section">
        <div class="contact-container">
            <h1>Contact</h1>
            <div class="row-contact-container"> 
                <div class="mail-contact">
                    <div style="background-image:url(/image/icons/mail.png)"></div>
                    <a href="mailto:{{mailSave}}"><p>{{mailSave}}</p></a>
                </div>
                <div class="form-section-contact">
                    {{ form_start(formView) }}
                        <div class="row-form-container">
                            <div class="input-form-container">
                                {{ form_widget(formView.name) }}
                                
                                <p>Votre nom</p>
                            </div>
                            <div class="input-form-container">
                                {{ form_widget(formView.firstname) }}
                                <p>Votre prénom</p>
                            </div>
                        </div>
                        <div class="row-form-container">
                            <div class="input-form-container">
                                {{ form_widget(formView.mail) }}
                                <p>Votre mail</p>
                            </div>
                            <div class="input-form-container">
                                {{ form_widget(formView.phone) }}
                                <p>Votre téléphone (facultatif)</p>
                            </div>
                        </div>
                        <div class="input-form-container">
                            {{ form_widget(formView.message) }}
                            <p>Votre message</p>
                        </div>
                            <div class="input-form-container-capcha">
                                {{ form_widget(formView.capcha) }}
                                <p>7+3 est égal à combien ?</p>
                            </div>
                        <p class="response-capcha">{{ error }}   {{ form_errors(formView) }}</p>
                        <button type='submit'>
                            Envoyer le message
                        </button>
                    {{ form_end(formView) }}
                </div>
            </div>
        </div>
        <div class='mentions-legales'>
            <p id="right-paragraph">©2022 Tous droits réservés Benoit Fabioux</p>

            <div>
                <a href="{{ path ('mentions_legales') }}">
                    <p>Mentions légales</p>
                </a>
                <a href="{{ path ('politiques_confidentialites') }}">
                    <p>Politique de confidentialités</p>
                </a>
            </div>
        </div>
    </section>
    <script> 
        let date = new Date();
        document.getElementById('right-paragraph').innerHTML = "©"+date.getFullYear()+" Tous droits réservés Benoit Fabioux";
        window.onload = wordCounter( '{{textBiographie}}' );
    </script>
{% endblock %}